openapi: 3.0.0
info:
  title: Lab Management API
  description: API for managing lab works and devices
  version: 1.0.0
servers:
  - url: http://localhost:5005
    description: Local development server
paths:
  /api/devices:
    get:
      summary: Get device information for classrooms
      description: Returns device information for specific classrooms in structured format
      responses:
        '200':
          description: Device information in structured format
          content:
            application/json:
              schema:
                type: object
                properties:
                  table:
                    type: object
                    properties:
                      headers:
                        type: array
                        items:
                          type: string
                        example: ["P224", "P344", "P411"]
                      rows:
                        type: array
                        items:
                          type: object
                          properties:
                            cells:
                              type: array
                              items:
                                type: object
                                properties:
                                  component_type:
                                    type: string
                                    description: Type of the component
                                    example: "Router"
                                  model:
                                    type: string
                                    description: Model of the component
                                    example: "Cisco 2900"
                                  text:
                                    type: string
                                    description: Display text for the device
                                    example: "R1-Cisco 2900 (G1)"
                                  status:
                                    type: string
                                    description: Status of the device
                                    enum: ["Active", "Free", "Inactive"]
                                    example: "Active"
                                  group_id:
                                    type: integer
                                    nullable: true
                                    description: Associated group ID if any
                                    example: 1
                                  backgroundColor:
                                    type: string
                                    description: Background color in HEX format
                                    example: "#FFFF00"
                                required:
                                  - text
                                  - backgroundColor
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/clear_db:
    post:
      summary: Clear database for a specific group
      description: Clears all data associated with a specific group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                group_id:
                  type: integer
                  description: ID of the group to clear
                  example: 1
              required:
                - group_id
      responses:
        '200':
          description: Success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Database cleared for group 1"
        '400':
          description: Missing or invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/run_lab:
    post:
      summary: Run a specific lab work
      description: Starts execution of a lab work for a specific group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lab_number:
                  type: integer
                  description: Number of the lab to run
                  example: 1
                vendor:
                  type: string
                  description: Vendor-specific implementation (optional)
                  example: "cisco"
                group_id:
                  type: integer
                  description: ID of the group running the lab
                  example: 1
              required:
                - lab_number
                - group_id
      responses:
        '200':
          description: Lab started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
        '400':
          description: Missing or invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: "error"
        message:
          type: string
          example: "Error description"