@startuml Последовательность работы системы
== Этап 1: Обнаружение оборудования ==
arp -> devices: Сканирование сети (ARP)
devices --> arp: IP, MAC, Vendor
arp -> db: Сохранение данных\n(обновление БД)

note right of arp
  <b>Периодическое сканирование</b>
  (каждые 5 минут)
  Обновляет актуальное состояние
  оборудования в БД
end note

== Этап 2: Аутентификация ==
user -> Moodle: Запуск лабораторной работы
Moodle -> auth: LTI Launch запрос
auth -> pnet: OpenID аутентификация
pnet --> auth: Подтверждение auth
auth --> Moodle: Перенаправление в PNETLab
user -> pnet: Работа в интерфейсе

== Этап 3: Получение топологии ==
pnet -> auth: Запрос файла топологии
auth -> rlk2: Запрос доступного оборудования
rlk2 -> db: Получение списка устройств
db --> rlk2: Список свободных устройств
rlk2 -> db: Бронирование оборудования
rlk2 -> rlk2: PnetLabParser\n(генерация UNL)
rlk2 --> auth: UNL файл топологии
auth --> pnet: Передача UNL файла

note left of rlk2
  <b>PnetLabParser</b> преобразует:
  1. Список устройств из БД
  2. Параметры лабораторной работы
  → в UNL-топологию
end note
@enduml